# Generated by Django 4.1.7 on 2023-03-29 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.CharField(blank=True, choices=[('general_store', 'General Store'), ('snacks', 'Snacks'), ('sweets', 'Sweets'), ('electronics', 'Electronics'), ('fruits', 'Fruits'), ('vegetables', 'Vegetables'), ('dairy', 'Dairy'), ('stationary', 'Stationary'), ('toys', 'Toys'), ('gifts', 'Gifts'), ('watch', 'Watch'), ('drinks', 'Drinks'), ('clothings', 'Clothings')], max_length=50, null=True),
        ),
    ]
