# Generated by Django 4.1.7 on 2023-03-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seller_name',
            field=models.CharField(default='', max_length=51),
        ),
    ]
