# Generated by Django 4.1.7 on 2023-03-11 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_registery_email_remove_registery_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registery',
            name='terms',
        ),
    ]
